#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
. "$(dirname "$0")/common.sh"

remote="$1"
url="$2"

z40=0000000000000000000000000000000000000000

while read local_ref local_sha remote_red remote_sha
do
	if [ "$local_sha" = $z40 ]
	then
		:
	else
		if [ "$remote_sha" = $z40 ]
		then
			range="$local_sha"
		else
			range="$remote_sha..$local_sha"
		fi

		commit=`git rev-list -n 1 --grep '^WIP' "$range"`

		if [ -n "$commit" ]
		then
			echo >&2 "Found WIP Commit in $local_ref, aborting"
			exit 1
		fi
	fi
done

exit 0
